### ISSUE TITLE
What is your #1 productivity tip?

### ISSUE THREAD

**Issue by sindresorhus** [jan-hendrik/ama#1]

**Comment by jan-hendrik** [comment]
Is this your initial set of questions you send anyone? :-)

#1: Inspect and adapt. Seriously. Don't just stick to your habbits. Validate where you can improve. decrease your keyboard timeouts, choose better tools, spend more time on the keyboard, less with your mouse. Follow other people in the same field and get inspired by them for further improvements.

**Comment by sindresorhus** [comment]
I've used it before, but I don't ask it to everyone.

**Comment by jan-hendrik** [comment]
:-)
